import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider as NextAuthSessionProvider } from "next-auth/react";
import { SessionProvider } from "@/contexts/session-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* NextAuth SessionProvider for update() functionality in login/register pages */}
        {/* Configured to not refetch automatically - we use our custom provider for data */}
        <NextAuthSessionProvider
          refetchInterval={0}
          refetchOnWindowFocus={false}
        >
          {/* Custom SessionProvider for optimized session fetching */}
          <SessionProvider>{children}</SessionProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
